#!/usr/bin/env bash
# ============================================================================
# install-langs.sh — Linux 服务器开发语言自动安装工具
# 支持: C/C++, Python, Node.js, Go
# 特性: 版本管理工具、国内镜像切换、错误日志
# ============================================================================
set -u -o pipefail

# ============================================================================
# 全局变量
# ============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ERROR_LOG="${SCRIPT_DIR}/error.log"
TIMESTAMP_FORMAT="%Y-%m-%dT%H:%M:%S%z"

# 镜像源
MIRROR_TUNA="https://mirrors.tuna.tsinghua.edu.cn"
MIRROR_ALIYUN="https://mirrors.aliyun.com"
NPM_MIRROR="https://registry.npmmirror.com"
GO_PROXY="https://goproxy.cn,direct"
NVM_NODE_MIRROR="https://npmmirror.com/mirrors/node"
CONDA_MIRROR="${MIRROR_TUNA}/anaconda/miniconda"

# 检测结果
OS_ID=""
OS_VERSION=""
PKG_MGR=""
ARCH=""
REAL_USER=""
IS_ROOT=false

# ============================================================================
# 日志函数
# ============================================================================
log_info() {
    printf "\033[0;32m[INFO]\033[0m  %s\n" "$*"
}

log_warn() {
    printf "\033[0;33m[WARN]\033[0m  %s\n" "$*"
}

log_error() {
    printf "\033[0;31m[ERROR]\033[0m %s\n" "$*"
}

log_step() {
    printf "\n\033[1;34m══════ %s ══════\033[0m\n" "$*"
}

# 写入错误日志
# 格式: timestamp level=ERROR lang=xxx phase=xxx exit=xxx msg="xxx"
log_error_to_file() {
    local lang="$1" phase="$2" exit_code="$3" msg="$4"
    local ts
    ts="$(date +"${TIMESTAMP_FORMAT}")"
    echo "${ts} level=ERROR lang=${lang} phase=${phase} exit=${exit_code} msg=\"${msg}\"" >> "${ERROR_LOG}"
}

# ============================================================================
# 系统检测
# ============================================================================
detect_os() {
    if [[ -f /etc/os-release ]]; then
        # shellcheck source=/dev/null
        . /etc/os-release
        OS_ID="${ID:-unknown}"
        OS_VERSION="${VERSION_ID:-unknown}"
    elif [[ -f /etc/redhat-release ]]; then
        OS_ID="centos"
        OS_VERSION=$(grep -oP '[0-9]+\.[0-9]+' /etc/redhat-release | head -1)
    else
        OS_ID="unknown"
        OS_VERSION="unknown"
    fi

    case "${OS_ID}" in
        ubuntu|debian|linuxmint|pop)
            PKG_MGR="apt" ;;
        centos|rhel|rocky|almalinux|fedora)
            if command -v dnf &>/dev/null; then
                PKG_MGR="dnf"
            else
                PKG_MGR="yum"
            fi ;;
        *)
            PKG_MGR="unknown" ;;
    esac

    ARCH="$(uname -m)"
    case "${ARCH}" in
        x86_64|amd64)  ARCH="amd64" ;;
        aarch64|arm64) ARCH="arm64" ;;
        *)             ARCH="unknown" ;;
    esac
}

detect_real_user() {
    if [[ -n "${SUDO_USER:-}" ]]; then
        REAL_USER="${SUDO_USER}"
    else
        REAL_USER="$(whoami)"
    fi

    if [[ "$(id -u)" -eq 0 ]]; then
        IS_ROOT=true
    fi
}

get_user_home() {
    eval echo "~${REAL_USER}"
}

# ============================================================================
# 网络检测与镜像切换
# ============================================================================
check_network() {
    local test_urls=("https://www.google.com" "https://github.com" "${MIRROR_TUNA}")
    for url in "${test_urls[@]}"; do
        if curl -sSf --connect-timeout 5 --max-time 10 "${url}" &>/dev/null; then
            return 0
        fi
    done
    return 1
}

# 检测是否需要使用国内镜像
should_use_mirror() {
    # 如果网络正常，测试官方源速度
    if curl -sSf --connect-timeout 5 --max-time 10 "https://go.dev" &>/dev/null; then
        return 1  # 不需要切换
    fi
    return 0  # 需要切换
}

switch_apt_mirror() {
    local mirror_url="${MIRROR_TUNA}/ubuntu"
    local sources_list="/etc/apt/sources.list"
    local backup="${sources_list}.bak.$(date +%s)"

    if grep -q "mirrors.tuna.tsinghua.edu.cn" "${sources_list}" 2>/dev/null; then
        log_info "APT 已使用清华镜像源"
        return 0
    fi

    log_info "切换 APT 到清华镜像源..."
    cp "${sources_list}" "${backup}"

    local codename
    codename=$(lsb_release -cs 2>/dev/null || echo "jammy")

    cat > "${sources_list}" <<EOF
# 清华大学镜像源 (auto-generated by install-langs.sh)
deb ${mirror_url} ${codename} main restricted universe multiverse
deb ${mirror_url} ${codename}-updates main restricted universe multiverse
deb ${mirror_url} ${codename}-backports main restricted universe multiverse
deb ${mirror_url} ${codename}-security main restricted universe multiverse
EOF

    if ! pkg_update 2>/dev/null; then
        log_warn "镜像源更新失败，恢复原始源..."
        cp "${backup}" "${sources_list}"
        pkg_update 2>/dev/null
        return 1
    fi
}

switch_yum_mirror() {
    local repo_dir="/etc/yum.repos.d"
    local backup_dir="${repo_dir}.bak.$(date +%s)"

    if ls "${repo_dir}"/*.repo &>/dev/null && grep -ql "mirrors.aliyun.com" "${repo_dir}"/*.repo 2>/dev/null; then
        log_info "YUM/DNF 已使用阿里云镜像源"
        return 0
    fi

    log_info "切换 YUM/DNF 到阿里云镜像源..."
    cp -r "${repo_dir}" "${backup_dir}"

    for repo_file in "${repo_dir}"/*.repo; do
        [[ -f "${repo_file}" ]] || continue
        sed -i 's|mirrorlist=|#mirrorlist=|g' "${repo_file}"
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://mirrors.aliyun.com|g' "${repo_file}"
    done

    if ! pkg_update 2>/dev/null; then
        log_warn "镜像源更新失败，恢复原始源..."
        rm -rf "${repo_dir}"
        mv "${backup_dir}" "${repo_dir}"
        return 1
    fi
}

# ============================================================================
# 包管理器抽象
# ============================================================================
pkg_update() {
    case "${PKG_MGR}" in
        apt) apt-get update -y ;;
        dnf) dnf makecache -y ;;
        yum) yum makecache -y ;;
        *)   log_error "不支持的包管理器: ${PKG_MGR}"; return 1 ;;
    esac
}

pkg_install() {
    local packages=("$@")
    case "${PKG_MGR}" in
        apt) apt-get install -y "${packages[@]}" ;;
        dnf) dnf install -y "${packages[@]}" ;;
        yum) yum install -y "${packages[@]}" ;;
        *)   log_error "不支持的包管理器: ${PKG_MGR}"; return 1 ;;
    esac
}

# ============================================================================
# 环境变量工具
# ============================================================================
# 追加行到文件（去重）
append_once() {
    local file="$1" line="$2"
    # 创建文件（如果不存在）
    touch "${file}" 2>/dev/null || true
    if ! grep -qF "${line}" "${file}" 2>/dev/null; then
        echo "${line}" >> "${file}"
    fi
}

# 确保 PATH 条目存在
ensure_path_entry() {
    local entry="$1"
    local profile_file="$2"
    append_once "${profile_file}" "export PATH=\"${entry}:\${PATH}\""
}

# 确保配置块存在（用标记包裹）
ensure_profile_block() {
    local file="$1" marker="$2"
    shift 2
    local content="$*"

    touch "${file}" 2>/dev/null || true
    if ! grep -qF "# >>> ${marker} >>>" "${file}" 2>/dev/null; then
        {
            echo ""
            echo "# >>> ${marker} >>>"
            echo "${content}"
            echo "# <<< ${marker} <<<"
        } >> "${file}"
    fi
}

# 下载文件（带重试和镜像回退）
download_file() {
    local url="$1" output="$2"
    local retries=2

    # 尝试原始 URL
    for ((i=1; i<=retries; i++)); do
        if curl -fsSL --connect-timeout 10 --max-time 300 -o "${output}" "${url}"; then
            return 0
        fi
        log_warn "下载失败 (尝试 ${i}/${retries}): ${url}"
        sleep 2
    done

    return 1
}

# ============================================================================
# 安装函数: C/C++
# ============================================================================
install_cpp() {
    log_step "安装 C/C++ 开发环境"

    case "${PKG_MGR}" in
        apt)
            pkg_install build-essential gcc g++ make gdb pkg-config cmake
            ;;
        dnf|yum)
            if dnf groupinstall -y "Development Tools" 2>/dev/null || \
               yum groupinstall -y "Development Tools" 2>/dev/null; then
                pkg_install gcc gcc-c++ make gdb cmake
            fi
            ;;
    esac
}

verify_cpp() {
    command -v gcc &>/dev/null && command -v g++ &>/dev/null && command -v make &>/dev/null
}

# ============================================================================
# 安装函数: Python
# ============================================================================
install_python_system() {
    log_step "安装 Python (系统版本)"

    case "${PKG_MGR}" in
        apt)
            pkg_install python3 python3-pip python3-venv python3-dev
            ;;
        dnf|yum)
            pkg_install python3 python3-pip python3-devel
            ;;
    esac

    # 配置 PyPI 国内镜像
    local user_home
    user_home="$(get_user_home)"
    local pip_conf="${user_home}/.config/pip/pip.conf"
    mkdir -p "$(dirname "${pip_conf}")"
    cat > "${pip_conf}" <<EOF
[global]
index-url = ${MIRROR_TUNA}/pypi/web/simple
trusted-host = mirrors.tuna.tsinghua.edu.cn
EOF
    chown "${REAL_USER}:${REAL_USER}" "${pip_conf}" 2>/dev/null || true
    log_info "已配置 PyPI 清华镜像源"
}

install_miniconda() {
    log_step "安装 Miniconda"

    local user_home
    user_home="$(get_user_home)"
    local install_dir="${user_home}/miniconda3"
    local installer="/tmp/miniconda.sh"

    # 检查是否已安装
    if [[ -d "${install_dir}" ]]; then
        log_warn "Miniconda 已安装于 ${install_dir}，跳过"
        return 0
    fi

    # 下载安装脚本
    local url="${CONDA_MIRROR}/Miniconda3-latest-Linux-${ARCH}.sh"
    if ! download_file "${url}" "${installer}"; then
        log_error "Miniconda 下载失败"
        return 1
    fi

    # 静默安装
    log_info "安装 Miniconda 到 ${install_dir}..."
    if ! bash "${installer}" -b -p "${install_dir}"; then
        log_error "Miniconda 安装失败"
        rm -f "${installer}"
        return 1
    fi
    rm -f "${installer}"

    # 配置 Conda 国内镜像
    local condarc="${user_home}/.condarc"
    cat > "${condarc}" <<EOF
channels:
  - defaults
show_channel_urls: true
default_channels:
  - ${MIRROR_TUNA}/anaconda/pkgs/main
  - ${MIRROR_TUNA}/anaconda/pkgs/r
  - ${MIRROR_TUNA}/anaconda/pkgs/msys2
custom_channels:
  conda-forge: ${MIRROR_TUNA}/anaconda/cloud
  pytorch: ${MIRROR_TUNA}/anaconda/cloud
EOF
    chown "${REAL_USER}:${REAL_USER}" "${condarc}" 2>/dev/null || true

    # 初始化 shell
    sudo -u "${REAL_USER}" "${install_dir}/bin/conda" init bash 2>/dev/null || true

    log_info "Miniconda 安装完成，已配置清华镜像源"
}

install_python() {
    # 先询问是否使用 Miniconda
    echo ""
    echo "  Python 安装选项:"
    echo "    1) 系统 Python + pip（推荐）"
    echo "    2) Miniconda（版本管理）"
    echo ""
    read -rp "  请选择 [1/2，默认 1]: " choice
    choice="${choice:-1}"

    case "${choice}" in
        1) install_python_system ;;
        2) install_miniconda ;;
        *) log_warn "无效选择，使用系统 Python"; install_python_system ;;
    esac
}

verify_python() {
    command -v python3 &>/dev/null || command -v conda &>/dev/null
}

# ============================================================================
# 安装函数: Node.js
# ============================================================================
install_nvm() {
    log_step "安装 nvm + Node.js"

    local user_home
    user_home="$(get_user_home)"
    local nvm_dir="${user_home}/.nvm"

    # 检查是否已安装
    if [[ -d "${nvm_dir}" ]]; then
        log_warn "nvm 已安装于 ${nvm_dir}"
        # 加载 nvm
        export NVM_DIR="${nvm_dir}"
        # shellcheck source=/dev/null
        [ -s "${nvm_dir}/nvm.sh" ] && . "${nvm_dir}/nvm.sh"
        return 0
    fi

    # 设置国内镜像
    export NVM_NODEJS_ORG_MIRROR="${NVM_NODE_MIRROR}"
    export NVM_DIR="${nvm_dir}"

    # 下载安装脚本
    local installer="/tmp/nvm-install.sh"
    if ! download_file "https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh" "${installer}"; then
        log_error "nvm 安装脚本下载失败"
        return 1
    fi

    # 以真实用户身份安装
    log_info "安装 nvm..."
    sudo -u "${REAL_USER}" bash "${installer}" 2>/dev/null
    rm -f "${installer}"

    # 加载 nvm
    # shellcheck source=/dev/null
    [ -s "${nvm_dir}/nvm.sh" ] && . "${nvm_dir}/nvm.sh"

    # 安装最新 LTS
    log_info "安装 Node.js LTS..."
    NVM_NODEJS_ORG_MIRROR="${NVM_NODE_MIRROR}" nvm install --lts 2>/dev/null || {
        log_warn "通过镜像安装失败，尝试官方源..."
        NVM_NODEJS_ORG_MIRROR="https://nodejs.org/dist" nvm install --lts 2>/dev/null
    }
    nvm use --lts 2>/dev/null || true
    nvm alias default lts/* 2>/dev/null || true

    # 配置 npm 国内镜像
    if command -v npm &>/dev/null; then
        sudo -u "${REAL_USER}" npm config set registry "${NPM_MIRROR}" 2>/dev/null || true
        log_info "已配置 npm 镜像源: ${NPM_MIRROR}"
    fi

    log_info "nvm + Node.js 安装完成"
}

verify_node() {
    command -v node &>/dev/null || {
        local user_home
        user_home="$(get_user_home)"
        [[ -s "${user_home}/.nvm/nvm.sh" ]]
    }
}

# ============================================================================
# 安装函数: Go
# ============================================================================
install_go() {
    log_step "安装 Go"

    # 获取最新版本
    local go_version
    go_version=$(curl -sSf "https://go.dev/VERSION?m=text" 2>/dev/null | head -1)
    if [[ -z "${go_version}" ]]; then
        go_version="go1.22.4"
        log_warn "无法获取最新版本，使用默认: ${go_version}"
    fi

    local go_tar="${go_version}.linux-${ARCH}.tar.gz"
    local install_dir="/usr/local"

    # 检查是否已安装相同版本
    if [[ -f "${install_dir}/go/bin/go" ]]; then
        local installed_version
        installed_version=$("${install_dir}/go/bin/go" version 2>/dev/null | awk '{print $3}')
        if [[ "${installed_version}" == "${go_version}" ]]; then
            log_info "Go ${go_version} 已安装，跳过"
            return 0
        fi
    fi

    # 下载
    local url="https://go.dev/dl/${go_tar}"
    local mirror_url="${MIRROR_ALIYUN}/golang/${go_tar}"
    local output="/tmp/${go_tar}"

    log_info "下载 Go ${go_version}..."
    if ! download_file "${url}" "${output}"; then
        log_warn "官方源下载失败，尝试阿里云镜像..."
        if ! download_file "${mirror_url}" "${output}"; then
            log_error "Go 下载失败（官方源和镜像均失败）"
            return 1
        fi
    fi

    # 清理旧版本并安装
    rm -rf "${install_dir}/go"
    log_info "解压 Go 到 ${install_dir}..."
    if ! tar -C "${install_dir}" -xzf "${output}"; then
        log_error "Go 解压失败"
        rm -f "${output}"
        return 1
    fi
    rm -f "${output}"

    # 配置环境变量
    local profile_file="/etc/profile.d/golang.sh"
    cat > "${profile_file}" <<'EOF'
export GOROOT=/usr/local/go
export GOPATH=${HOME}/go
export PATH=${GOROOT}/bin:${GOPATH}/bin:${PATH}
EOF
    chmod 644 "${profile_file}"

    # 为当前用户也配置
    local user_home
    user_home="$(get_user_home)"
    local user_profile="${user_home}/.bashrc"
    ensure_path_entry "/usr/local/go/bin" "${user_profile}"
    append_once "${user_profile}" 'export GOPATH="${HOME}/go"'
    ensure_path_entry '${GOPATH}/bin' "${user_profile}"
    chown "${REAL_USER}:${REAL_USER}" "${user_profile}" 2>/dev/null || true

    # 配置 Go 代理
    append_once "${user_profile}" "export GOPROXY=${GO_PROXY}"
    chown "${REAL_USER}:${REAL_USER}" "${user_profile}" 2>/dev/null || true

    log_info "Go ${go_version} 安装完成，已配置 GOPROXY=${GO_PROXY}"
}

verify_go() {
    command -v go &>/dev/null || [[ -f /usr/local/go/bin/go ]]
}

# ============================================================================
# 通用安装/验证包装器
# ============================================================================
run_language_step() {
    local lang="$1" func_name="$2" verify_func="$3"
    local start_time
    start_time=$(date +%s)

    log_info "开始安装 ${lang}..."

    if "${func_name}"; then
        # 验证安装
        if "${verify_func}"; then
            local elapsed=$(( $(date +%s) - start_time ))
            log_info "✅ ${lang} 安装成功 (${elapsed}s)"
            return 0
        else
            log_warn "${lang} 安装完成但验证失败"
            log_error_to_file "${lang}" "verify" 1 "installation completed but verification failed"
            return 1
        fi
    else
        local exit_code=$?
        log_error "${lang} 安装失败 (exit code: ${exit_code})"
        log_error_to_file "${lang}" "install" "${exit_code}" "installation function returned non-zero"
        return ${exit_code}
    fi
}

# ============================================================================
# 交互菜单
# ============================================================================
show_menu() {
    echo ""
    echo "╔══════════════════════════════════════════════╗"
    echo "║     Linux 开发语言自动安装工具              ║"
    echo "╠══════════════════════════════════════════════╣"
    echo "║  可安装的语言:                              ║"
    echo "║    1) C/C++ (gcc, g++, make, cmake)        ║"
    echo "║    2) Python (系统版本 或 Miniconda)        ║"
    echo "║    3) Node.js (通过 nvm)                    ║"
    echo "║    4) Go                                    ║"
    echo "║                                              ║"
    echo "║  特殊选项:                                  ║"
    echo "║    a) 全部安装                               ║"
    echo "║    q) 退出                                   ║"
    echo "╚══════════════════════════════════════════════╝"
    echo ""
}

parse_selection() {
    local input="$1"
    local selections=()

    # 全部安装
    if [[ "${input}" == "a" || "${input}" == "A" ]]; then
        echo "cpp python node go"
        return
    fi

    # 解析数字选择
    for char in $(echo "${input}" | grep -o .); do
        case "${char}" in
            1) selections+=("cpp") ;;
            2) selections+=("python") ;;
            3) selections+=("node") ;;
            4) selections+=("go") ;;
            q|Q) echo "quit"; return ;;
            *) ;; # 忽略无效输入
        esac
    done

    # 去重
    printf '%s\n' "${selections[@]}" | sort -u | tr '\n' ' '
}

# ============================================================================
# 主流程
# ============================================================================
main() {
    echo ""
    log_info "Linux 开发语言自动安装工具 v1.0"
    echo ""

    # 系统检测
    detect_os
    detect_real_user

    log_info "系统: ${OS_ID} ${OS_VERSION}"
    log_info "架构: ${ARCH}"
    log_info "包管理器: ${PKG_MGR}"
    log_info "用户: ${REAL_USER}"

    # 权限检查
    if ! ${IS_ROOT}; then
        log_error "此脚本需要 root 或 sudo 权限运行"
        log_error "请使用: sudo $0"
        exit 1
    fi

    # 包管理器检测
    if [[ "${PKG_MGR}" == "unknown" ]]; then
        log_error "不支持的 Linux 发行版: ${OS_ID}"
        log_error "支持: Ubuntu, Debian, CentOS, RHEL, Rocky, AlmaLinux"
        exit 1
    fi

    # 网络检测与镜像切换
    log_step "网络检测"
    if should_use_mirror; then
        log_warn "检测到网络问题，尝试切换国内镜像源..."
        case "${PKG_MGR}" in
            apt)     switch_apt_mirror ;;
            dnf|yum) switch_yum_mirror ;;
        esac
    else
        log_info "网络连接正常"
    fi

    # 更新包索引
    log_info "更新包索引..."
    pkg_update 2>/dev/null || log_warn "包索引更新失败，继续执行..."

    # 显示菜单并获取选择
    show_menu
    read -rp "请输入选项 (如 1,3 或 a 全部安装): " user_input
    local selections
    selections=$(parse_selection "${user_input}")

    if [[ "${selections}" == "quit" ]]; then
        log_info "用户取消，退出"
        exit 0
    fi

    if [[ -z "${selections}" ]]; then
        log_error "未选择任何语言，退出"
        exit 1
    fi

    # 确认安装
    echo ""
    log_info "将安装以下语言: ${selections}"
    read -rp "确认继续? [Y/n]: " confirm
    if [[ "${confirm}" =~ ^[nN] ]]; then
        log_info "用户取消，退出"
        exit 0
    fi

    # 初始化错误日志
    echo "# install-langs.sh 错误日志 - $(date +"${TIMESTAMP_FORMAT}")" > "${ERROR_LOG}"
    echo "# 格式: timestamp level=ERROR lang=xxx phase=xxx exit=xxx msg=\"xxx\"" >> "${ERROR_LOG}"
    echo "" >> "${ERROR_LOG}"

    # 执行安装
    local total=0
    local success=0
    local failed=0
    local failed_list=()

    for lang in ${selections}; do
        ((total++))
        case "${lang}" in
            cpp)
                if run_language_step "C/C++" install_cpp verify_cpp; then
                    ((success++))
                else
                    ((failed++))
                    failed_list+=("C/C++")
                fi
                ;;
            python)
                if run_language_step "Python" install_python verify_python; then
                    ((success++))
                else
                    ((failed++))
                    failed_list+=("Python")
                fi
                ;;
            node)
                if run_language_step "Node.js" install_nvm verify_node; then
                    ((success++))
                else
                    ((failed++))
                    failed_list+=("Node.js")
                fi
                ;;
            go)
                if run_language_step "Go" install_go verify_go; then
                    ((success++))
                else
                    ((failed++))
                    failed_list+=("Go")
                fi
                ;;
        esac
    done

    # 输出汇总
    echo ""
    log_step "安装汇总"
    log_info "总计: ${total}  成功: ${success}  失败: ${failed}"

    if [[ ${failed} -gt 0 ]]; then
        log_warn "失败的语言: ${failed_list[*]}"
        log_warn "详细错误请查看: ${ERROR_LOG}"
    fi

    if [[ ${success} -gt 0 ]]; then
        log_info "请运行 'source ~/.bashrc' 或重新登录以使环境变量生效"
    fi

    echo ""
}

# ============================================================================
# 入口
# ============================================================================
main "$@"
